[server]
port = 6379
log_level = 1

[persist]
mode = 3
rdb_file = ../data/kvstore.rdb
rdb_save_interval = 300
rdb_min_changes = 100
rdb_save_on_shutdown = true
aof_file = ../data/kvstore.aof
aof_rewrite_size = 1
aof_auto_rewrite = true

[replication]
enabled = false
role = master
; master_ip = 127.0.0.1
; master_port = 6379